# Rustfmt configuration for Synton-lang

edition = "2021"
hard_tabs = false
tab_spaces = 2
max_width = 100
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
license_template_path = ""
wrap_comments = true
comment_width = 80
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
struct_lit_single_line = true
emit_lifetime = true
enum_discrim_align_threshold = 0
struct_field_align_threshold = 0
struct_variant_width = 35
array_width = 60
attr_fn_like_width = 70
chain_width = 60
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
fn_args_layout = "Tall"
fn_call_width = 80
fn_single_line = false
where_single_line = false
force_explicit_abi = true
format_macro_matchers = true
format_macro_bodies = true
hex_literal_case = "Lower"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
merge_derives = true
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
short_array_element_width_threshold = 10
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_old_structure_guess = false
version = "Two"
